In [1]:
from sklearn.datasets import fetch_openml

from sklearn.preprocessing import OrdinalEncoder

In [2]:
data = fetch_openml('car' , as_frame = True).frame

d:\ML basics\myenv\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)

In [3]:
data.head(6)

  buying  maint doors persons lug_boot safety binaryClass
0  vhigh  vhigh     2       2    small    low           P
1  vhigh  vhigh     2       2    small    med           P
2  vhigh  vhigh     2       2    small   high           P
3  vhigh  vhigh     2       2      med    low           P
4  vhigh  vhigh     2       2      med    med           P
5  vhigh  vhigh     2       2      med   high           P

Ordinal Encoding

In [4]:
columns_to_encode = ['lug_boot' , 'safety']

encoder = OrdinalEncoder(
    categories = [['small', 'med' , 'big'] , ['low' , 'med' , 'high']]

)

data[columns_to_encode] = encoder.fit_transform(data[columns_to_encode])

In [5]:
data.tail(7)

     buying maint  doors persons  lug_boot  safety binaryClass
1721    low   low  5more    more       0.0     2.0           N
1722    low   low  5more    more       1.0     0.0           P
1723    low   low  5more    more       1.0     1.0           N
1724    low   low  5more    more       1.0     2.0           N
1725    low   low  5more    more       2.0     0.0           P
1726    low   low  5more    more       2.0     1.0           N
1727    low   low  5more    more       2.0     2.0           N

In [8]:
data[columns_to_encode] = encoder.inverse_transform(data[columns_to_encode])

In [9]:
data.tail()

     buying maint  doors persons lug_boot safety binaryClass
1723    low   low  5more    more      med    med           N
1724    low   low  5more    more      med   high           N
1725    low   low  5more    more      big    low           P
1726    low   low  5more    more      big    med           N
1727    low   low  5more    more      big   high           N

One hot encoding